#include <stdio.h>
#include <stdlib.h>

int main()
{
   printf("\n************     FUNCTIONS     ***************\n");
   printf("\n\n Function is a group of statements that perform a specific task. the main objective is to avoid the repetition of codes in a program.\n It provides modularity code re-usability.\n");
   printf("\n• A C program is a collection of one or more functions where one of the function must be main().\n");
   printf("• Execution of program always starts and ends with main.\n");
   printf("•  main can call other functions to do some part of the task.\n");
   printf("     Advantages of Functions :\n");
   printf("• Problems can be divided into understandable steps.\n");
   printf("• They help in code reuse.\n");
   printf(" ->for eg if average of numbers needs to be calculated 5 times in a program, with different data, instead of writing the same codes  5times in program, the cod can be called 5 times.\n");
   printf("• C library provides standard functions that make programming easier.\n");
   printf("• Functions can also be protected data by defining data as local data. This ensures that the data is available only to the function and cannot be manipulated outside the function.\n");
   printf("\n Types of function :\n") ;
   printf("Functions can be broadly classified into two types\n");
   printf("• Built in function\n");
   printf("• User defined function\n");
   printf(" Built in function\n");
   printf("         c language provides many built in functions few of them are listed below:\n");
   printf("• Strings manipulation function(discussed in the section 2 of module).\n");
   printf("• Character manipulation functions.\n");
   printf("• Memory management functions(discussed in the section of the module 5).\n");
   printf("• Mathematical function.\n");
   printf("character management functions: This header file includes character manipulation functions is ctype.h(#include\"type.h\")");
   printf("\n  ___________________________________________________________\n");
   printf("  | functions       | Return true if ch is                  |\n");
   printf("  |_________________|_______________________________________|\n");
   printf("  | isalnum(ch)     |A letter of alphabet(upr or lwr)or num |\n");
   printf("  | isalpha(ch)     |An upr or lwr case letter of alphabet  |\n");
   printf("  | isascii(ch)     |An ASCII value in the range of 0 to 127|\n");
   printf("  | isblanck(ch)    |A tab, space or another blank character|\n");
   printf("  | islower(ch)     |A lowercase letter of alphabet,a to z  |\n");
   printf("  | isupper(ch)     |A uppercase letter of alphabet,a to z  |\n");
   printf("  |  Function       |         Return                        |\n");
   printf("  | toascii(ch)     |An ASCII value in the range of 0 to 127|\n");
   printf("  | tolower(ch)     |A lowercase of character ch            |\n");
   printf("  | toupper(ch)     |A uppercase of character ch            |\n");
   printf("  |_________________|_______________________________________|\n");
   printf("\n\n Mathematical Functions :\n   The header file that includes mathematical functions is math .h (#include<math.h>)\n\n");
   printf("\n  ___________________________________________________________\n");
   printf("  | functions       | Return                                |\n");
   printf("  |_________________|_______________________________________|\n");
   printf("  | fabs(n)         |absolute value of floating point number|\n");
   printf("  | ceil(n)         |smallest integer value is >= n         |\n");
   printf("  | floor(n)        |largest integer value is <= n          |\n");
   printf("  | exp(n)          |e raised to given power n              |\n");
   printf("  | log(n)          |natural logarithm to base e            |\n");
   printf("  | log10(n)        | common logarithm to base e            |\n");
   printf("  | pow(x,n)        | x raised to the given power n         |\n");
   printf("  | sqrt(n)         |square root of n                       |\n");
   printf("  | cbrt(n)         |  cube root of n                       |\n");
   printf("  |  sin(n)         | sine value of n                       |\n");
   printf("  |  cos(n)         | cosine value of n                     |\n");
   printf("  |  sinh(n)        | hyperbolic sine value of n            |\n");
   printf("  |  cosh(n)        | hyperbolic cosine value of n          |\n");
   printf("  |_________________|_______________________________________|\n");
   printf(" The built function available in c are defined under the header files.\n\n");
   printf(" Header file:\n  A header file containing c declaration and macro definitions to be to be shared between several source .We use header in program by including it, with c preprocessing directive '#include'\n\n\n");
   printf("     stdio.h         input /output functions                                     \n");
   printf("     math.h          mathematical  functions                                     \n");
   printf("     string.h        string manipulation                                         \n");
   printf("     stdlib.h        standard library functions                                  \n");
   printf("     malloc.h        memory allocation/deal location function                    \n");
   printf("     time.h          computing time  functions                                   \n");
   printf("     stddef.h        common macro functions                                      \n");
   printf("     float.h         allow to use constant related to floating point             \n");
   printf("     ctype.h         allow to use functions of testing and mapping characters    \n");
   printf("     conio.h         library function for performing console input and output    \n");
   printf("     User defined functions :\n");
   printf(" The built in functions provided by c are not sufficient for performing customized functions, hence c allows user to create their own functions to perform specific task these are called as user defined functions\n");
   printf("In the below example without using functions ,addition  performed directly after reading inputs ,but in the example using functions,add(a,b) function is called which makes the control to move to the example function add(int a, int b) which computes sum and then returns. the remainder value in the variable sum and then displayed.\n");
   printf(" Example : C program to add two numbers\n");
   printf("/* without functions*/                           |   /*with user defined function*/                    \n");
   printf("     #include<stdio.h>                           |       #include stdio.h                              \n");
   printf("     #include<conio.h>                           |       #include conio.h                              \n");
   printf("     void main()                                 |       int add(int a,int b);                         \n");
   printf("     {                                           |       {                                             \n");
   printf("     int sum a,b;                                |       int sum a,b;                                  \n");
   printf("     printf(\"enter a and b\");                    |       printf(\"enter a and b\");                    \n");
   printf("     scanf(\"%%d%%d\",&a,&b);                        |       scanf(\"%%d%%d\",&a,&b);                      \n");
   printf("     sum=a+b;                                    |       sum=add(a,b);                                 \n");
   printf("     printf(\"sum is %d\",sum);                    |       printf(\"sum is %d\",sum);                    \n");
   printf("     getch();                                    |       getch();                                      \n");
   printf("     }                                           |       }                                             \n");
   printf("                                                 |       int add(int a,int b)                          \n");
   printf("                                                 |       {                                             \n");
   printf("                                                 |       int sum;                                      \n");
   printf("                                                 |       sum=a+b;                                      \n");
   printf("                                                 |       return sum;                                   \n");
   printf("                                                 |       }                                             \n");
   printf(" Advantages of user defined functions \n");
   printf(" •can be used in number of places without restrictions as compared to store procedures.\n");
   printf(" •code can be made less complicated and made easier.\n");
   printf(" •parameters can be made passed to the function.\n");
   printf(" •reduction in size of the program code of function can be used again and again by calling it.\n");
   printf(" •program becomes easy to understand and debug.\n");
   printf(" •a function can be shared by other programs by compiling this separately and loading and linking them together.\n");
   printf(" •in C recursive function can call itself. Many calculations can be done easily by using recursive functions such as calculation of factorial of number etc.\n");
   printf("\n Location of functions in a program \n");
   printf("\n____________________________________________________________________________________________________");
   printf("\n|types     |pictorial representation                   |Example                                    |");
   printf("\n|__________|___________________________________________|___________________________________________|");
   printf("\n|          |       ____________________                | #include<stdio.h>                         |");
   printf("\n|          |       |#include and funct|                | int add(int a,int b);    (optional)       |");
   printf("\n|          |       | declational(opt) |                | int add(int a,int b)                      |");
   printf("\n|          |       |__________________|                | {                                         |");
   printf("\n|   1      |                |                          |  int sum ;                                |");
   printf("\n|          |       _________|__________                |  sum=a+b;                                 |");
   printf("\n|          |       | function of body |                |  return sum;                              |");
   printf("\n|          |       |__________________|                | }                                         |");
   printf("\n|          |                |                          |  void main()                              |");
   printf("\n|          |          ______|_________                 |  {                                        |");
   printf("\n|          |          | main program |                 |  int sum a,b;                             |");
   printf("\n|          |          |______________|                 |  a=10,b=20;                               |");
   printf("\n|          |                                           |  sum=add(a,b);                            |");
   printf("\n|          |                                           |  printf(\"sum is %%d\",sum);                 |");
   printf("\n|          |                                           |  }                                        |");
   printf("\n|__________|___________________________________________|___________________________________________|");
   printf("\n|          |       ____________________                | #include<stdio.h>                         |");
   printf("\n|          |       |#include and funct|                | int add(int a,int b);    (mandatory)      |");
   printf("\n|          |       | declational(mand)|                | void main()                               |");
   printf("\n|          |       |__________________|                | {                                         |");
   printf("\n|   2      |                |                          |  int sum a,b;                             |");
   printf("\n|          |          ______|_________                 |  a=10,b=20;                               |");
   printf("\n|          |          | main program |                 |  sum=add(a,b);                            |");
   printf("\n|          |          |______________|                 |  printf(\"sum is %%d\",sum);                 |");
   printf("\n|          |                |                          | }                                         |");
   printf("\n|          |        ________|___________               | int add(int a,int b)                      |");
   printf("\n|          |        | function of body |               | {                                         |");
   printf("\n|          |        |__________________|               |  int sum ;                                |");
   printf("\n|          |                                           |  sum=a+b;                                 |");
   printf("\n|          |                                           |  return sum;                              |");
   printf("\n|          |                                           |  }                                        |");
   printf("\n|__________|___________________________________________|___________________________________________|");
   printf("\n Location of function refers to the placement of the function definition in relation to the main program .There are mainly two ways to place a program:\n");
   printf(" •type 1:placing a function first followed by placing the entire program.\n");
   printf(" •type 2:placing function declaration before main program followed by main program and the followed by function body.\n");
   printf("\n\n Structure of a function :\n");
   printf("\n Function is a group of statements that together to perform a specific task.\n Structure of a function is explained by taking an example of a program to display in element of array using functions.\n");
   printf("\n\n /*program to display  'n' elements of array*/\n");
   printf("#include<stdio.h>\nvoid display(int b[10]);\nint n;\nvoid main()\n{\n int i,a[10];\n printff(\"enter the number of elements\"); \n scanf(\"%%d \",&n);\n printf(\"enter elements \\n\");for(i=0;i<n;i++)\n scanf(\"%%d\",&a[i]);\n printf(\"element are\");\n display(a);\n getch();\n}\nvoid display(int b[10])\n{\n int i;\n for(i=0;i<n;i++)\n  print(\"%%d\",&b[i]);\n}\n");
   printf(" \n\n Program to compute the factorial of a given number n using recursion*/\n");
   printf(" #include\"stdio.h\" \n int fact(int);\n void main()\n {\n  int n ,ans;\n  printf(\"enter the value of n\");\n  scanf(\"%%d\",&n);\n  ans=fact(n);\n  printf(\"ans=%%d\",ans);\n  getch();\n }\n");
   printf(" int fact(int n )\n {\n  if(n==0)\n  {\n   return 1;\n  }\n  else\n  {\n   return n*fact(n-1);\n  }\n }\n");
   printf("\n METHOD:\n factorial(5)=5*factorial(4)\n 5*4*factorial(3)\n 5*4*3*factorial(2)\n 5*4*3*2*factorial(1)\n 5*4*3*2*1*factorial(0)\n 5*4*3*2*1*1\n");
   printf("\n Output :\n  enter the value of n\n  5\n  ans=120");
   printf("\n\n------------------*----------------------\n");
   printf("\n\n /* Example for string passing by reference or call by reference*/\n");
   printf(" #include<stdio.h>\n void display(char ch[]);\n void main()\n {\n  char c[20];\n  printf(\"enter the string\");\n  gets(c);\n  display(c); /*passing entire string c to function */\n }\n");
   printf(" void display(char ch[])\n {\n  printf(\"string is:\");\n  puts(ch); /*display enter string at a time*/\n\n");
   printf(" Recursive Function :\n");
   printf(" •Recursive function are there function that call themselves during than execution until certain conditions are satisfied.\n");
   printf(" •note while using recursion.programs need to be careful to define an exit condition from the recursion function ,otherwise it will go in infinite loop'\n");
   printf("                 __________________\n") ;
   printf("          ------>||rec_function()||\n");
   printf("          |      ||______________||\n");
   printf("     _____|_____         |         \n");
   printf("     | body    |        /\\  \n");
   printf("     |_________| no    /is\\ \n");
   printf("          |___________/exit\\\n");
   printf("                      \\cond/ \n");
   printf("                       \\  /  \n");
   printf("                        \\/ yes\n");
   printf("                   _____|_____\n") ;
   printf("                   | stop    |\n");
   printf("                   |_________|\n");
   printf("\n\n Passing Array in a Function :\n");
   printf(" •Array elements or an entire array can be passed to a function.\n");
   printf(" •If we pass the values stored in an array ,single element at a time ,then it is called array passing by values or call by values.\n");
   printf("\n /*example for array passing by value or call by value*/\n");
   printf(" #include<stdio.h>\n #include<conio.h>\n void display(int p);\n void main()\n {\n  int n,i,a[10];\n  printf(\"enter the number of elements \\n\");\n  scanf(\"%%d\",&n);\n  printf(\"enter the elemnts\");\n  for(i=0;i<n;i++)\n   display(a[i]);\n  }\n  setch(); }\n");
   printf(" void display(int p)\n {\n  printf(\"%%d\\t\" ,p);\n }\n/* display the element it recieves */\n");
   printf("\n /* in call by value we pass the value of single value at a time not an entire array. For every elements display() function is called*/\n\n");
   printf(" Output :\n enter the number of elements\n 5\n enter the elements\n 1 2 3 4 5\n the elements are\n 1 2 3 4 5\n\n");
   printf("\n Call By Reference Or Parameter Passing By Reference:\n");
   printf(" •When an address of the variable is passed to the function during its invocation, then function is called is call by reference or parameter passing by reference.");
   printf("/* call by reference*/\n");
   printf("\n #include<stdio.h>\n int add(int *i,int *j);\n void main()\n {                       /*call function invokes function add()\n");
   printf(" int sum ,a=10 b=20;     and passes the address of variables a and b as parameters.\n sum=add(&a,&b);         Here the address of a and b are the actual parameters*/\n");
   printf(" printf(\"sum is %%d \",sum);\n getch()\n }\n");
   printf(" int add(int *i,int *j){     /* here *i and *j are the address of a and b as the actual parameters which are holding the respective\n   int sum;                  values stored in which address are passed as actual parameters.\n");
   printf("   sum= *i+*j;               using which user defined function add() computers sum and returns a value\n   return sum;               sum to calling a function*/\n }\n\n");
   printf(" •Instead of values of a and b ,address of a and b are passed and reference *i,*j recieves the values of a and b and preform addition operation .This concept is called call by reference or parameter passing by reference.\n");
   printf("\n\n Passing strings in Functions:\n");
   printf(" •Strings are declared in c in similar manner as arrays.\n Only difference is that,strings are char type.\n Strings can be passed to function or similar manner as arrays as, string is also an array.\n");
   printf("\n /* example for String passing by value or call by value*/\n");
   printf(" #include<stdio.h>\n void main()\n {\n  char c[50];  printf(\"enter the string \");\n  scanf(\"%%s\",c);\n for(i=0;c[i]!='\\0';i++)\n  {\n   display(c[i]);   /*passing single character of string at a time to function */\n  }\n getch();\n }\n");
   printf(" void display(char ch)\n {\n  putchar(ch);   /*display single character at a time*/\n }\n");
   printf("\n\n Function with arguments but no return value :\n");
   printf(" •Parameter are passed from calling to the called function.\n");
   printf(" •Called function does not return a value it jut performs the specified action.\n");
   printf(" /* Program to illustrate functions with parameter but no return*/\n");
   printf(" #include<stdio.h>\n #include<conio.h>\n int addition(int ,int ,int)\n void main()\n {\n int a,b,c;\n clrscr();\n printf(\"enter the value of a,b,c\");\n scanf(\"%%d%%d%%d\",&a,&b,&c);\n addition(a,b,c);\n getch()\n }\n");
   printf(" void  addition(int x,int y,int z)\n {\n int s;\n s=x+y+z;\n printf(\"sum of three no.s=%%d\",s);\n }\n\n\n");
   printf(" output: \n enter the value of a,b and c\n 10 20 30\n sum of three no.s=60\n\n\n");
   printf(" Parameter Passing Mechanism :\n");
   printf(" C supports two techniques for passing parameter from one function to another, namely\n");
   printf(" i)  Pass by value also know as call by value.\n");
   printf(" ii) pass by reference also known as call by reference\n\n\n");
   printf(" Call By Value Or Parameter During By value\n\n");
   printf(" •When a variable as a value is passed to the function during its execution,the function execution is called as call by value or pass by value\n\n");
   printf(" /* call by value*/\n");
   printf(" #include<stdio.h>\n int add(int i,int j);\n void main()\n {\n  int sum,a=10,b=20;\n  sum=add(a,b);\n  printf(\"sumis %%d\",sum);\n  getch()\n }\n int add(int i,int j)\n {\n int sum;\n sum=i+j;\n return sum;\n }\n");
   printf(" •that is a and to the actual parameter,when the function add(s,b) is called the value of actual parameter is except is formed parameter is function definition i and j, this method is without call by value or parameter passed by value\n");
   printf("\n\n Functions with No Arguments and No return Value :\n");
   printf(" •No parameter is passed from calling function to the called function.\n");
   printf(" •called function dose not return any value.\n");
   printf(" /* Program illustrate function with no return no parameter no return value*/\n");
   printf(" #include<stdio.h>\n #include<conio.h>\n void addition()\n void main()\n {\n  clrscr();\n  addition()\n  getch()\n }\n");
   printf(" void addition()\n {\n  int a,b,c,s;\n  printf(\"enter the value of a,b,c\");\n  scanf(\"%%d%%d%%d\",&a,&b,&c);\n  s=a+b+c;\n  printf(\"the sum of three no.s=%%d\",s);\n }\n");
   printf("\n\n /*program to illustrate static variable*/\n\n");
   printf(" #include<stdio.h>\n #include<conio.h>\n void display();\n void main()\n {\n  display();\n  display();\n  display();\n  display();\n  display();\n }\n void display()\n {\n static int i=0;\n i++\n printf(\"%%d\\n\",i);\n }\n\n\n");
   printf(" Category of Function :\n");
   printf("                                                     _______________________                           \n");
   printf("                                                     |category of function |                           \n");
   printf("                                                     |_____________________|                           \n");
   printf("             __________________________________________________|_______________________________________\n");
   printf("    _________|_________        ___________|____________         ___________|__________       _________|_________\n");
   printf("    |function with no |        |function with argument|         |function with argume|       |function with no |\n");
   printf("    |argument and no  |        |but no return value   |         |nts and with return |       |argument but with|\n");
   printf("    |return value     |        |                      |         |value               |       |return value     |\n");
   printf("    |_________________|        |______________________|         |____________________|       |_________________|\n");
   printf(" Function with No Arguments But Return A value :\n");
   printf(" •No parameter is passed from calling function to the called function, but function returns a value.\n\n\n");
   printf(" /* program to illustrate functions without parameter with returning value*/\n\n");
   printf(" #include<stdio.h>\n #include<conio.h>\n int addition(); void main()\n {\n  int r;\n  clrscr();\n  r=addition();\n  printf(\"sum of three no.s=%%d\",r);\n  getch();\n }\n");
   printf(" int addition()\n {\n  int a,b,c,s;\n  printf(\" enter the value of a,b and c\");\n  scanf(\"%%d%%d%%d\",&a,&b,&c);\n  s=a+b+c;\n  return s;\n }\n\n\n");
   printf(" Function with argument and with return value :\n");
   printf(" •Parameter are passed from calling function to the called function and based on the received parameter values called function performs required action and return a value.\n");
   printf(" /* program to illustrate functions with parameter and with return value */\n");
   printf(" #include<stdio.h>\n #include<conio.h>\n int addition(int,int,int);\n void main() {\n  int a,b,c,r;\n  clrscr();\n  printf(\"enter the value of a,b and c\");\n  scanf(\"%%d%%d%%d\",&a,&b,&c);\n  r=addition(a,b,c);\n  printf(\"sum of three no.s=%%d\",r);\n  getch();\n }\n");
   printf(" int addition(int x,int y,int z)\n {\n int s; s=x+y+z;\n return s;\n }\n\n\n output:\n enter the value of a,b,c\n 10 20 30\n sum of three no.s=60\n\n\n");
   printf(" Actual and Formal parameters :\n");
   printf(" •Actual parameters are parameters which are found in signature(call) of a given function. These are the parameter transfered from the calling function to the called function\n");
   printf(" •formal parameter are parameter which are found in the definition(body) of a given function.\n\n");
   printf(" Local and Global Variables :\n");
   printf("_____________________________________________________________________\n");
   printf("|        | Global variable               |  Local variable          |\n");
   printf("|________|_______________________________|__________________________|\n");
   printf("|   1)   | global variables are created  |local variables are create|\n");
   printf("|        |outside all functions at the   |d inside a function       |\n");
   printf("|        | begining of a program.        |                          |\n");
   printf("|   2)   |Global variable are accessible |Local variable are accessi|\n");
   printf("|        |to all the functions present in|ble to only that respectiv|\n");
   printf("|        |in the program.                |e function inside which   |\n");
   printf("|        |                               |they have been created    |\n");
   printf("|   3)   |if no value is given to a globl|if no value is given to a |\n");
   printf("|        |variable by the programmer then|local variable then it hol|\n");
   printf("|        |automatically it is assigned a |d a junk value.           |\n");
   printf("|        |value O.                       |                          |\n");
   printf("|   4)   |global variable are alive for  |local variable are alive  |\n");
   printf("|        |the entire duration of exceutio|only for the duration of  |\n");
   printf("|        |n of the program.              |execution of the function |\n");
   printf("|        |                               |inside which they are     |\n");
   printf("|        |                               |present                   |\n");
   printf("|________|_______________________________|__________________________|\n");
   printf("\n\n Register Variable :\n");
   printf(" •Register variable are such variable which are allotted space not in the main memory but in one of the cpu's register. For a compiler to allocate space for variable in a cpu register the variable has to be declared as\n");
   printf("     register int i;\n");
   printf(" •The Advantage of storing a variable in cpu register is that the variable can be accessed much faster. Hence the speed of execution of program increases.\n");
   printf(" •note :The declaration register int i is just a request by the programmer to the compiler to allocate a cpu register for i\n");
   printf(" if no cpu register are free available to the compiler, then the compiler would ignore that request and allocate space to the variable i as any other normal local variable\n");
   printf("\n\n Static Variables :\n");
   printf(" •Static variables are declared using the keyword static they can be declared outside the function or inside the function\n");
   printf(" •Memory is allocated to these variables once\n");
   printf(" •If static variables are defined inside the function, they cannot be accessed outside the function.\n");
   printf(" •A function cannot use static variable which are declared in any other function.\n");
   printf("         static int i=0;    \n");
   printf(" •Multiple actual parameter are separated by comma.\n\n\n /*program to illustrate adding two no.s*/\n\n");
   printf(" ______________________________________________________________________\n");
   printf(" |/*without user defined function */ | /*with user defined function */|\n");
   printf(" | #include<stdio.h>                 | #include<stdio.h>              |\n");
   printf(" | #include<conio.h>                 | #include<conio.h>              |\n");
   printf(" | void main()                       | int add(int a,int b);          |\n");
   printf(" | {                                 | void main()                    |\n");
   printf(" | int a,b,sum;                      | {                              |\n");
   printf(" | printf(\"enter a and b\");          | int sum,a,b;                   |\n");
   printf(" | scanf(\"%%d%%d\",&a,&b);              | printf(\"enter a and b\");       |\n");
   printf(" | sum=a+b;                          | scanf(\"%%d%%d\",&a,&b);           |\n");
   printf(" | printf(\"sum is %%d\",sum);          | sum=add(a,b);                  |\n");
   printf(" | getch();                          | printf(\"sum is %%d\",sum);       |\n");
   printf(" | }                                 | getch();                       |\n");
   printf(" |                                   | }                              |\n");
   printf(" |                                   | int add(int a,int b)           |\n");
   printf(" |                                   | {                              |\n");
   printf(" |                                   | int sum;                       |\n");
   printf(" |                                   | sum = a + b;                   |\n");
   printf(" |                                   | return sum;                    |\n");
   printf(" |                                   | }                              |\n");
   printf(" |___________________________________|________________________________|\n\n\n");
   printf(" •Formal parameter list gives the input for the operation to be performed by function.\n");
   printf(" •local variables one variables used only within a function.\n");
   printf(" •Return statements returns result of function.\n");
   printf(" •Statements one to perform specific operation.\n");
   printf("\n\n\n Function Declaration:\n");
   printf("\n\n •It consist of only the function header with\n 1)return_type 2)function_name 3)formal_parameter\n");
   printf(" •function declaration is terminated with a semicolon.\n");
   printf(" •If the function has multiple patterns, separate each of them with commas.\n");
   printf(" •Identifiers name are not required, but can be used for better readability.\n");
   printf(" •These identifier names also need not to match with the ones.\n");
   printf(" •Function declaration  is placed in global declaration section before main.\n");
   printf("\n\n\n Function Call :\n");
   printf("\n •It consist of function_name,parenthesis ie() ,and actual parameters\n");
   printf(" The actual parameter must match the formal parameter in type and order in the parameter list.\n");
   printf("\n\n User-defined Functions :\n");
   printf(" •The function written or defined by programmer are called as user-defined function.\n");
   printf(" •A function name is used 3 times ;\n");
   printf("  1)during function declaration\n  2)in the function call\n  3)in function definition\n\n");
   printf(" Function Definition :\n");
   printf(" •It contains the code for a function  and consist of\n 1)function header 2)function body\n");
   printf(" syntax\n   return_type function_name(formal_parameter list)\n   {\n    local declaration;\n    statements;\n    return(expression);\n   }\n");
   printf("\n\n where,\n   •return_type is the data type of value that function returns, it may be int ,char ,float,etc. If it dose not return anything then return_type is void.\n");
   printf("  •function_name is the actual name of the function\n");
}
