#include <stdio.h>
#include <stdlib.h>

int main()
{
    printf("\n ********** pointer **********\n\n");
    printf(" Pointer Definition: Pointer is a variable that holds the address of another variable.\n");
    printf("\n Declaration and Initialization of Pointer\n\n");
    printf(" The operators used to represent pointer are :\n • Address operator(&)\n • Indirection operator(*)\n");
    printf(" syntax :\n ptr_data_type *ptr_variable_name\n ptr_variable_name =& variable_name \n");
    printf(" where variable_name is variable whose address has to be stored in pointer.\n");
    printf(" example :\n int a=10;\n int *ptr;\n then   ptr =&a;\n      *ptr =a;\n that is ptr is a pointer holding address of variable 'a' and *ptr holds the value of a.\n");
    printf("\n example program:\n #include<stdio.h>\n #include<conio.h>\n void main()\n {\n  int a=10;\n  int *ptr;\n  ptr=&a;\n  printf(\"%%d\\n\",a);\n  printf(\"%%d\\n\",&a);\n  printf(\"%%d\\n\",ptr);\n  printf(\"%%d\\n\",*ptr);\n  getch();\n }\n");
    printf(" output :\n 10\n  2056\n 2056\n 10\n\n");
    printf(" Pointers and Function ( call by reference):\n\n");
    printf(" Call by reference method involves use of address of variables as actual parameter in calling function and pointer variable with (*) indirection operator is used at called function to perform required operation that is formal parameters\n\n");
    printf(" /* consider an example of swapping two numbers using call by reference or using pointers*/\n\n");
    printf(" #include<stdio.h>\n #include<conio.h>\n void main()\n {\n  int x=10, y=20;\n  swap( &x,&y);\n  printf(\"after swapping :\\n=%%d\\ny=%%d\",x,y);\n  getch();\n }\n");
    printf(" void swap(int *a,int *b)\n {\n  int temp;\n  temp= *a;\n  *a=*b;  *b=temp;\n }\n\n output :\n  after swapping :\n  x=20\n  y=10\n\n");
    printf("\n Pointers and Array :\n\n");
    printf(" The operations performed using array concept can also be done using pointers.\n");
    printf(" Syntax:\n  data_type *ptr_name;\n  ptr_name = &array_name or ptr_name =array_name;\n\n");
    printf(" Here pointers dose not point to all the element of array,instead initially it points to the first example of an array later which is increment to get other elements\n\n");
    printf("example\n int a[10]={11,12,13,14};\n int *ptr;\n ptr =&a or ptr=a; here ptr is a pointer pointing to 11 initially.\n it can be explained using program below.\n\n");
    printf(" /*program to demonstrate pointers to arrays concept */\n");
    printf(" #include<stdio.h>\n #include<conio.h>\n void main()\n {\n  int a[10]={11,12,13,14};\n  int *ptr;\n  ptr=a;  /* initially pointing to first element 11 */\n");
    printf("  for(i=0;i<4 ;i++)  /*four elements */\n  {\n   printf(\"%%d\\t\",a[i]);\n   printf(\"%%d\\n\",&a[i]);\n   printf(\"%%d\\t\",*ptr);\n   printf(\"%%d\\t\",ptr);\n   ptr++;\n   /*making ptr to point next value by doing ptr=ptr+1*/\n  }\n getch();\n }\n");
    printf("output:\n 11 2056 /*value a[0] pointed by ptr at first iteration and address where that value is stored */\n");
    printf(" 11 2056 /*value *ptr pointed by ptr at first iteration and address where that value is stored */\n");
    printf(" 12 2058 /*value a[1] pointed by ptr at second iteration and address where that value is stored */\n");
    printf(" 12 2058 /*value *ptr pointed by ptr at first iteration and address where that value is stored */\n");
    printf(" 13 2060 /*value a[2] pointed by ptr at third iteration and address where that value is stored */\n");
    printf(" 13 2060 /*value *ptr pointed by ptr at first iteration and address where that value is stored */\n");
    printf(" 14 2062 /*value a[3] pointed by ptr at fourth iteration and address where that value is stored */\n");
    printf(" 15 2062 /*value *ptr pointed by ptr at first iteration and address where that value is stored */\n");
    printf(" _____________________\n");
    printf(" |11  |12  |13  |14  |      since integer type occupies 2 bytes for each element\n");
    printf(" |____|____|____|____|      If it reserves 2056 for first element as starting address 2056+2 =2058 as\n");
    printf(" |2056|2058|2060|2062|      second element's starting address 2058+2=2060 for third elements and so on.\n");
    printf(" |____|____|____|____|\n\n");
    printf("position    0   1     2    3\n");
    printf("         _____________________\n");
    printf("values   |11  |12  |13  |14  |\n");
    printf("         |____|____|____|____|\n");
    printf("address  |2056|2058|2060|2062|\n");
    printf("         |____|____|____|____|\n");
    printf("            |ptr\n");
    printf(" at i=0 a[0]=11,&a[0]=2056\n  *ptr=11,ptr=2056\n  i++,ptr++\n  i=1,ptr=2058\n\n");
    printf("position    0   1     2    3\n");
    printf("         _____________________\n");
    printf("values   |11  |12  |13  |14  |\n");
    printf("         |____|____|____|____|\n");
    printf("address  |2056|2058|2060|2062|\n");
    printf("         |____|____|____|____|\n");
    printf("                |ptr\n");
    printf(" at i=1 a[1]=12,&a[1]=2058\n  *ptr=12,ptr=2058\n  i++,ptr++\n  i=2,ptr=2060\n\n");
    printf("position    0   1     2    3\n");
    printf("         _____________________\n");
    printf("values   |11  |12  |13  |14  |\n");
    printf("         |____|____|____|____|\n");
    printf("address  |2056|2058|2060|2062|\n");
    printf("         |____|____|____|____|\n");
    printf("                      |ptr\n");
    printf(" at i=2 a[2]=13,&a[2]=2060\n  *ptr=13,ptr=2060\n  i++,ptr++\n  i=3,ptr=2062\n\n");
    printf("position    0   1     2    3\n");
    printf("         _____________________\n");
    printf("values   |11  |12  |13  |14  |\n");
    printf("         |____|____|____|____|\n");
    printf("address  |2056|2058|2060|2062|\n");
    printf("         |____|____|____|____|\n");
    printf("                          |ptr\n");
    printf(" at i=3 a[3]=14,&a[3]=2056\n  *ptr=14,ptr=2062\n  i++,ptr++\n  i=4,ptr=2064\n\n");
    printf("\n\n  Character Pointer and Function or Pointer To Strings\n\n");
    printf(" Strings are array of characters instead of integer values of array, here pointer pointers to the character present in string represented as an array.\n");
    printf(" Syntax :\n Data_type &ptr_name ;\n ptr_name = string_name;\n example\n char str[20]=\"america\";\n char *ptr;\n ptr=str;\n\n");
    printf(" Here pointer dose not point to all the character of string, instead of initially it points to all first elements or first character of a string later which is incremented to get other elements it can be explained using below program\n");
    printf("\n /* string copy using pointer to string concept (using single pointer)\n*/\n\n");
    printf(" #include<stdio.h>\n #include<conio.h>\n void main()\n {\n  int i;\n  int str1[10]=\"sanju\";\n  int str2[10];\n  int *ptr;\n  ptr=str1;\n  for(i=0;str1[i]!='\\0';i++)\n  {\n   str2[i]=*ptr;\n   ptr++;\n  }\n  str2[i]='\\0';\n  printf(\"strings2 after coping is %%s\",str2);\n  getch();\n }\n");
    printf("output:\n strings after coping is nanju\n");
    printf("position    0   1     2    3\n");
    printf("         _______________________________\n");
    printf("character|s   |a   |n   |j   |u   |\\0  |    since integer type occupies 1 bytes for each element\n");
    printf("         |____|____|____|____|____|____|    If it reserves 2051 for first element as starting address 2051+1 =2052 as\n");
    printf("address  |2051|2052|2053|2054|2055|2056|    second element's starting address 2052+1=2053 for third elements and so on.\n");
    printf("         |____|____|____|____|____|____|\n");
    printf("            |ptr\n\n\n");
    printf("         _______________________________\n");
    printf("character|s   |a   |n   |j   |u   |\\0  |\n");
    printf("         |____|____|____|____|____|____|\n");
    printf("address  |2051|2052|2053|2054|2055|2056|\n");
    printf("         |____|____|____|____|____|____|\n");
    printf("            |ptr\n");
    printf(" at i=0 str1[0]!='\\0'\n str2[0]=*ptr=s\n i++=1,ptr++=2052\n\n");
    printf("         _______________________________\n");
    printf("character|s   |a   |n   |j   |u   |\\0  |\n");
    printf("         |____|____|____|____|____|____|\n");
    printf("address  |2051|2052|2053|2054|2055|2056|\n");
    printf("         |____|____|____|____|____|____|\n");
    printf("                |ptr\n");
    printf(" at i=1 str1[1]!='\\0'\n str2[1]=*ptr=a\n i++=2,ptr++=2053\n\n");
    printf("         _______________________________\n");
    printf("character|s   |a   |n   |j   |u   |\\0  |\n");
    printf("         |____|____|____|____|____|____|\n");
    printf("address  |2051|2052|2053|2054|2055|2056|\n");
    printf("         |____|____|____|____|____|____|\n");
    printf("                     |ptr\n");
    printf(" at i=2 str1[2]!='\\0'\n str2[2]=*ptr=n\n i++=3,ptr++=2054\n\n");
    printf("         _______________________________\n");
    printf("character|s   |a   |n   |j   |u   |\\0  |\n");
    printf("         |____|____|____|____|____|____|\n");
    printf("address  |2051|2052|2053|2054|2055|2056|\n");
    printf("         |____|____|____|____|____|____|\n");
    printf("                           |ptr\n");
    printf(" at i=3 str1[3]!='\\0'\n str2[3]=*ptr=j\n i++=4,ptr++=2055\n\n");
    printf("         _______________________________\n");
    printf("character|s   |a   |n   |j   |u   |\\0  |\n");
    printf("         |____|____|____|____|____|____|\n");
    printf("address  |2051|2052|2053|2054|2055|2056|\n");
    printf("         |____|____|____|____|____|____|\n");
    printf("                                |ptr\n");
    printf(" at i=4 str1[4]!='\\0'\n str2[4]=*ptr=u\n i++=5,ptr++=2056\n\n");
    printf("         _______________________________\n");
    printf("character|s   |a   |n   |j   |u   |\\0  |\n");
    printf("         |____|____|____|____|____|____|\n");
    printf("address  |2051|2052|2053|2054|2055|2056|\n");
    printf("         |____|____|____|____|____|____|\n");
    printf("                                    |ptr\n");
    printf(" at i=5 str1[5]=='\\0'\n  so here iterations stops since while (str1[i]=='\\0'\n\n");
    printf("\n Pointer To Pointer \n");
    printf(" Pointer is a variable that stores the address of another variable.pointer storing the address of another pointer, that is pointer pointing to another pointer is called as pointer to pointer.\n declaration ;\n data_type **pointer_name;\n\n");
    printf(" Initialization :\n  pointer_name = &another_pointer_name\n The below example demonstrate pointer to pointer concept\n");
    printf(" int a=10;\n int *ptr1,**ptr2;\n ptr1=&a;\n ptr2=&ptr1; /*ptr2 is the pointer to the another pointer ptr1*/\n\n");
    printf("                                  ptr2           ptr1            a\n");
    printf("                                 ______         ______           ______\n");
    printf("value stored in pointer          |1283|-------->|2056|---------->|10  |\n");
    printf("                                 |____|         |____|           |____|\n");
    printf("address where pointer             356           1283              2056\n");
    printf(" value is stored        address of ptr2    address of ptr2    address of a\n\n");
    printf(" #include<stdio.h>\n #include<conio.h>\n void main()\n {\n  int a=10;\n  int *ptr1,**ptr2;\n  ptr1=&a;\n  ptr2=&ptr1;\n  printf(\"%%d\\n\",a);------->10\n  printf(\"%%d\\n\",&a);------->2056\n  printf(\"%%d\\n\",ptr1);------->2056\n  printf(\"%%d\\n\",&ptr1);------->1283\n  printf(\"%%d\\n\",*ptr1);------->10\n  printf(\"%%d\\n\",ptr2);------->1283\n  printf(\"%%d\\n\",*ptr2);------->2056\n  printf(\"%%d\\n\",**ptr2);------->10\n  getch();\n }\n");
    printf(" Address Arithmetic :\n 1.An integer value can be added or subtracted from a pointer. It can be incremented or incremented \n array\n");
    printf("         _____________________\n");
    printf("         |11  |12  |13  |14  |\n");
    printf("         |____|____|____|____|\n");
    printf("         |2050|2052|2064|2056|\n");
    printf("         |____|____|____|____|\n");
    printf(" #include<stdio.h>\n #include<conio.h>\n void main()\n {\n  int a[4]={11,9,8,14};\n  int *ptr;\n  ptr=&a;------->output\n  printf(\"%%d\\n\",ptr);------->2050\n  printf(\"%%d\\n\",*ptr);------->11\n  ptr++;/*incrementing*/\n  printf(\"%%d\\n\",ptr);------->2052\n  printf(\"%%d\\n\",* ptr);------->9\n  ptr--;/*decrementing*/\n  printf(\"%%d\\n\",ptr);------->2050\n  printf(\"%%d\\n\",*ptr);------->11\n  getch();\n }\n");
    printf("\n\n Advantages and Disadvantage of pointer \n\n advantages\n • Pointer provide direct access to memory\n • pointer provide a way to return more than one value to the function\n • Reduces the storage space and complexity of program\n • Reduces the execution time of program\n");
    printf(" • Provides an alternate way to access array elements\n • pointers can be used to pass information back and fourth between the calling function and called function.\n ");
    printf("\n disadvantages\n • Uninitialized pointers might cause segmentation fault\n • Dynamically allocated block needs to be freed explicitly, Otherwise it would lead to memory leak\n • pointers are slower than normal variables\n");
    printf(" • if pointer are updated with incorrect values, it might lead to memory corruption\n\n\n");
    printf(" write a c program to read n elements to an array and print those elements using pointer to array\n");
    printf(" #include<stdio.h>\n #include<conio.h>\n void main()\n {\n  int a[100],*ptr,i;\n  printf(\"enter number of elements\");\n  scanf(\"%%d\",&n);\n  ptr=a;\n  for(i=0;i<n;i++)\n  {\n   scanf(\"%%d\",ptr);\n   ptr++;\n  }\n  ptr=a;\n  printf(\"array elements are\");\n  for(i=0;i<n;i++)\n  {\n   printf(\"%%d\",ptr);\n   ptr++;\n  }\n  getch();\n }\n");
    printf(" output :\n  enter the nu. of elements\n  5\n  11 12 13 14 15\n  array elements are\n  11 12 13 14 15\n\n\n");
    printf(" Dynamic Memory Allocation\n\n");
    printf(" The processor of allocation of memory size at is called as dynamic memory allocation.\n");
    printf(" mainly there are four functions for memory management,namely:\n  • malloc()\n  • calloc()\n  • free()\n  • realloc()\n\n\n");
    printf(" malloc() : It allocates memory from a freely available memory and returns a pointer to a block of contiguous memory of specific size.\n");
    printf(" syntax : pointer_name =(data_type *)malloc(byte_size);\n example \n int *a;\n a=(int *)malloc(20);\n\n");
    printf(" calloc() : It allocates memory for array elements and initialize them to zero and also returns a pointer to memory.\n");
    printf(" syntax : pointer_name =(data_type *)calloc(n,size); where n is no. of memory blocks,size is the size of blocks to be allocated in bytes\n example \n int *a;\n a=(int *)calloc(5,2);\n\n");
    printf(" free() :  free function is used to free the memory blocks allocated by malloc and calloc.\n");
    printf(" syntax : free(pointer_name);\n example \n int *ptr;\n free(ptr);\n\n");
    printf(" realloc() : It is used to modify the size of already allocated memory block.\n");
    printf(" syntax : pointer_name =realloc(pointer_name,new_size);\n example \n int *ptr;\n a=(int *)realloc(ptr,4);\n\n");
    printf(" Program to demonstrate allocating memory at runtime using malloc()\n");
    printf(" here array of elements are stored in dynamically allocated memory without any static allocation of size.\n");
    printf(" #include<stdio.h>\n #include<conio.h>\n void main()\n {\n  int *ptr,n,i;  printf(\"enter number of elements\");\n  scanf(\"%%d\",&n);\n  ptr= (int *)malloc(n*sizeof(int));\n  for(i=0;i<n;i++)\n  {\n   scanf(\"%%d\",ptr+i);\n  }\n  printf(\"array elements are\");\n  for(i=0;i<n;i++)\n  {\n   printf(\"%%d\",ptr);\n   ptr++;\n  }\n  getch();\n }\n\n");
    printf(" output\n if we give n=2\n ptr=(int *)malloc(2*sizeof(int));/*allocate 4 bytes memory block */\n");
    printf("        i=     0             1    \n");
    printf("         ____________________________________\n");
    printf("         |                  |               |\n");
    printf("    |--> |__________________|_______________|\n");
    printf("   ptr    2bytes(2056)       2bytes(2058)\n");
    printf(" at i=0\n scanf(\"%%d\",ptr+i)\n stores now elements to ptr+i=2056+0=2056 location\n\n at i=1 scanf(\"%%d\",ptr+i)\n stores now elements to ptr+i=2056+1=2058 location\n similarly printing is done using *(ptr+1)\n\n\n");


}
